server:
  port: 8801
  tomcat:
    uri-encoding: utf-8
spring:
  aop:
    auto: true
    proxy-target-class: false
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
logging:
  level: info